services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - ENV=production
    depends_on:
      - frontend

  frontend:
    build: ./project
    ports:
      - "5173:5173"
    volumes:
      - ./project:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev", "--", "--host"]