services:
  postgres:
    image: ankane/pgvector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./project/public/maps:/app/project/public/maps
    environment:
      - ENV=production
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=mydatabase
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypassword
    depends_on:
      - frontend
      - postgres
    networks:
      - app_network


  frontend:
    build: ./project
    ports:
      - "5173:5173"
    volumes:
      - ./project:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app_network
    command: ["npm", "run", "dev", "--", "--host"]

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
