name: Run Tests (Frontend + Backend)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Frontend setup
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./project

      - name: Run frontend tests with Vitest
        run: npm run test
        working-directory: ./project

      # Backend setup
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Of de versie die je gebruikt

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
        working-directory: ./

      - name: Run backend tests with pytest
        run: |
          pytest backend/tests --maxfail=1 --disable-warnings -q
        working-directory: ./
